# Generated by Django 3.0.7 on 2020-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=150)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('pdf_body', models.FileField(upload_to='Pdf Files')),
                ('title', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField()),
            ],
        ),

    ]
