# Generated by Django 3.0.7 on 2020-06-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='Username',
        ),
    ]
